#Google Analytics
analytics-id: #leave blank to not use Analytics

#Subtitle
subtitle:
  active: true
  text: 미분양주택수로 알아보는 현재 부동산 시장 현황

#Nav 
nav:
  pages:
    active: true
  social:
    active: true

#Featured images in homepage
featured-img:/seoul.png
  active: true

#Show categories at the end of posts
categories:
  active: true

#Show date and read time under the post title
date-under-post:
  active: true

#Use MathJAX
mathjax:
  active: true

#Show related posts based on categories
related-posts:
  active: true
  title: "You May Also Enjoy"

#Comments
comments: true
